package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.mycompany.theknife.clientTK;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

/// Classe che gestisce la finestra per la rimozione di ristoranti dalla lista preferiti.
public class DettaglioPreferiti extends JDialog {
    private JButton BottonRimuovi;
    private JLabel TestoRimuovi;
    private JPanel PanelDP;

    private final int idRistorante;
    private final String nomeUtente;

    /// @param parent         Jdialog padre
    /// @param idRistorante   int id del ristorante
    /// @param nomeRistorante String nome del ristorante
    /// @param nomeUtente     String username dell' utente
    public DettaglioPreferiti(JDialog parent, int idRistorante, String nomeRistorante, String nomeUtente) {
        super(parent, "Elimina ristorante preferito", true);
        this.idRistorante = idRistorante;
        this.nomeUtente = nomeUtente;

        setContentPane(PanelDP);

        // Spaziatura perimetrale
        PanelDP.setBorder(new EmptyBorder(20, 25, 20, 25));

        // Styling della label con testo centrato HTML
        if (TestoRimuovi != null) {
            TestoRimuovi.setText("<html><div style='text-align: center; font-family: sans-serif; font-size: 11pt; color: #2C3E50;'>" +
                    "Vuoi rimuovere <b>" + nomeRistorante + "</b> dai preferiti?</div></html>");
        }

        // Styling del pulsante di rimozione (rosso)
        if (BottonRimuovi != null) {
            BottonRimuovi.setFont(new Font("SansSerif", Font.BOLD, 12));
            BottonRimuovi.setForeground(new Color(192, 57, 43)); // Rosso per eliminazione
            BottonRimuovi.setCursor(new Cursor(Cursor.HAND_CURSOR));
            BottonRimuovi.addActionListener(e -> rimuoviDaPreferiti());
        }

        pack(); // Adatta le dimensioni automaticamente
        setLocationRelativeTo(parent);
    }

    /// Effetua l' eliminazione del ristorante dai preferiti.
    private void rimuoviDaPreferiti() {
        int conferma = JOptionPane.showConfirmDialog(this,
                "Sei sicuro di voler rimuovere questo ristorante dai preferiti?",
                "Conferma Rimozione",
                JOptionPane.YES_NO_OPTION);

        if (conferma != JOptionPane.YES_OPTION) return;

        String[] pacchetto = {"RIMUOVI_PREFERITO", nomeUtente, String.valueOf(idRistorante)};
        String risposta = clientTK.inviaRichiesta(pacchetto);

        if (risposta != null) {
            JOptionPane.showMessageDialog(this, risposta, "Esito", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, risposta, "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelDP = new JPanel();
        PanelDP.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        TestoRimuovi = new JLabel();
        TestoRimuovi.setText("Voiu rimuovere il seguente ristorante dai preferiti?");
        PanelDP.add(TestoRimuovi, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        BottonRimuovi = new JButton();
        BottonRimuovi.setText("Rimuovi Ristorante");
        PanelDP.add(BottonRimuovi, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelDP;
    }

}