package gui;

import javax.swing.*;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.mycompany.theknife.clientTK;

/// Classe per la gestione della finestra di dialogo che consente l'eliminazione di un ristorante
public class EliminaRistorante extends JFrame {
    private JTextField txtid;
    private JButton elimina;
    private JPanel mainPanel;

    private String username;
    private homePageU homeParent; // Riferimento alla Home

    /// @param u      String username del ristoratore
    /// @param parent homePageU riferimento alla home
    public EliminaRistorante(String u, homePageU parent) {
        this.username = u;
        this.homeParent = parent;

        if (mainPanel == null) {
            throw new IllegalStateException("Il mainPanel non è stato associato correttamente");
        }

        setContentPane(mainPanel);
        setTitle("Eliminazione ristorante - TheKnife");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // 1. Spaziatura perimetrale pulita per non far toccare gli elementi ai bordi
        mainPanel.setBorder(new EmptyBorder(20, 25, 20, 25));

        // 2. Bordo moderno con padding interno per il campo ID
        CompoundBorder campoTestoStyle = new CompoundBorder(
                new LineBorder(new Color(189, 195, 199), 1, true),
                new EmptyBorder(6, 10, 6, 10)
        );

        if (txtid != null) {
            txtid.setFont(new Font("SansSerif", Font.PLAIN, 12));
            txtid.setBorder(campoTestoStyle);
        }

        // 3. Styling del pulsante (Azione distruttiva = Testo Rosso)
        if (elimina != null) {
            elimina.setFont(new Font("SansSerif", Font.BOLD, 12));
            elimina.setForeground(new Color(192, 57, 43)); // Rosso elegante per richiamare attenzione
            elimina.setCursor(new Cursor(Cursor.HAND_CURSOR));
            elimina.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    verificaEliminazione(txtid.getText());
                }
            });
        }

        // Adatta la finestra ai nuovi margini senza deformare la griglia
        pack();
        setLocationRelativeTo(parent);
    }

    /// @param id String contenente id del ristorante da eliminare
    /// Controlla che il valore inserito sia valido e poi procede a eliminare il ristorante dal db
    private void verificaEliminazione(String id) {
        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inserisci un ID.", "Valore non inserito", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!id.trim().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Id non valido. Inserisci solo numeri.", "Valore non consentito", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Integer i = clientTK.inviaRichiesta(new String[]{"ELIMINA_RISTORANTE", username, id.trim()});

        if (i != null && i > 0) {
            JOptionPane.showMessageDialog(this, "Ristorante eliminato con successo.", "Operazione conclusa", JOptionPane.INFORMATION_MESSAGE);

            // AGGIORNIAMO LA TABELLA DELLA HOME!
            if (homeParent != null) {
                homeParent.aggiornaVistaProprietario();
            }

            this.dispose(); // Chiudiamo la finestrella
        } else {
            JOptionPane.showMessageDialog(this, "Impossibile eliminare. Verifica l'ID o i permessi.", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Inserire identificatore del ristorante da eliminare");
        mainPanel.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtid = new JTextField();
        mainPanel.add(txtid, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("id:");
        mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        elimina = new JButton();
        elimina.setText("Elimina");
        mainPanel.add(elimina, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}