/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Balkaran
 */
public class paginaIniziale extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(paginaIniziale.class.getName());

    /**
     * Creates new form paginaIniziale
     */
    public paginaIniziale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottoneLogin = new javax.swing.JButton();
        bottoneRegistazione = new javax.swing.JButton();
        labelGuest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bottoneLogin.setText("Login");
        bottoneLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bottoneLoginMouseEntered(evt);
            }
        });
        bottoneLogin.addActionListener(this::bottoneLoginActionPerformed);

        bottoneRegistazione.setText("Registrazione");
        bottoneRegistazione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bottoneRegistazioneMouseEntered(evt);
            }
        });
        bottoneRegistazione.addActionListener(this::bottoneRegistazioneActionPerformed);

        labelGuest.setText("continua come Guest");
        labelGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelGuestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelGuestMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bottoneRegistazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottoneLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(bottoneLogin)
                .addGap(18, 18, 18)
                .addComponent(bottoneRegistazione)
                .addGap(18, 18, 18)
                .addComponent(labelGuest)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuestMouseEntered
        labelGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelGuestMouseEntered

    private void labelGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuestMouseClicked
        //RICHIEDERE IL DOMICILIO O LUOGO E POI MANDARLO ALLA HOMEPAGE
    }//GEN-LAST:event_labelGuestMouseClicked

    private void bottoneLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottoneLoginMouseEntered
        bottoneLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR) {});
    }//GEN-LAST:event_bottoneLoginMouseEntered

    private void bottoneLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneLoginActionPerformed
        //APRIRE IL JDIALOG PER IL LOGIN
    }//GEN-LAST:event_bottoneLoginActionPerformed

    private void bottoneRegistazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneRegistazioneActionPerformed
        // APRIRE IL JDIALOG PER LA REGISTRAZIONE
    }//GEN-LAST:event_bottoneRegistazioneActionPerformed

    private void bottoneRegistazioneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottoneRegistazioneMouseEntered
        bottoneRegistazione.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR) {});
    }//GEN-LAST:event_bottoneRegistazioneMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneLogin;
    private javax.swing.JButton bottoneRegistazione;
    private javax.swing.JLabel labelGuest;
    // End of variables declaration//GEN-END:variables
}
