package gui;

import javax.swing.*;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import java.awt.*;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.mycompany.theknife.clientTK;

/// Gestisce la schermata per l'inserimento della posizione degli utenti guest
public class richiestaPosGuest extends JDialog {
    private JPanel mainPanel;
    private JTextField nomeCitta;
    private JTextField nomeNazione;
    private JButton invioButton;

    // Variabile mantenuta dal branch "modifiche" per chiudere la Home correttamente
    private boolean successo = false;

    /// @param padre J_Frame padre
    public richiestaPosGuest(JFrame padre) {
        super(padre, "Inserisci Posizione", true);

        if (mainPanel == null) {
            throw new IllegalStateException("Il mainPanel non è stato associato correttamente nel file .form");
        }
        setContentPane(mainPanel);

        // 1. Spaziatura perimetrale pulita e proporzioni Dialog
        mainPanel.setBorder(new EmptyBorder(20, 25, 20, 25));
        setSize(380, 250);
        setResizable(false);

        // 2. Bordo moderno con padding interno per i campi di testo
        CompoundBorder campoTestoStyle = new CompoundBorder(
                new LineBorder(new Color(189, 195, 199), 1, true),
                new EmptyBorder(6, 10, 6, 10)
        );

        if (nomeCitta != null) {
            nomeCitta.setFont(new Font("SansSerif", Font.PLAIN, 12));
            nomeCitta.setBorder(campoTestoStyle);
        }

        if (nomeNazione != null) {
            nomeNazione.setFont(new Font("SansSerif", Font.PLAIN, 12));
            nomeNazione.setBorder(campoTestoStyle);
        }

        // 3. Styling del pulsante Invio
        if (invioButton != null) {
            invioButton.setText("Cerca Ristoranti");
            invioButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
            invioButton.setFont(new Font("SansSerif", Font.BOLD, 12));
            invioButton.addActionListener(e -> apriHomePageU());
        }

        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(padre);
    }

    /// Controlla i valori inseriti e se sono accettabili procede all'apertura
    /// della schermata homepage
    private void apriHomePageU() {
        String citta = (nomeCitta != null) ? nomeCitta.getText().trim() : "";
        String nazione = (nomeNazione != null) ? nomeNazione.getText().trim() : "";

        if (citta.isEmpty() || nazione.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Inserire sia la città che la nazione.",
                    "Attenzione: Dati Mancanti",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String[] richiesta = {"POSIZIONE", citta, nazione};
        String rispServer = clientTK.inviaRichiesta(richiesta);
        System.out.println("[DEBUG] COORDINATE RICEVUTE: " + rispServer);

        if (rispServer == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Domicilio non riconosciuto",
                    "Accesso Ospite",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        JOptionPane.showMessageDialog(
                this,
                "Stai accedendo come ospite.\nAlcune funzionalità potrebbero essere limitate.",
                "Accesso Ospite",
                JOptionPane.INFORMATION_MESSAGE
        );

        successo = true; // Impostiamo a true per far chiudere la Home
        new homePageU(null, rispServer).setVisible(true);
        this.dispose();
    }

    /// Metodo getter necessario alla classe Home
    public boolean getSuccesso() {
        return successo;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Città");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(128, 27), null, 0, false));
        nomeCitta = new JTextField();
        mainPanel.add(nomeCitta, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        invioButton = new JButton();
        invioButton.setText("Invio");
        mainPanel.add(invioButton, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nomeNazione = new JTextField();
        mainPanel.add(nomeNazione, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Nazione");
        mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(128, 27), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}